### Dan Krasnonosenkikh, Cameron Scoons, Aaditya Watwe

In [1]:
from datetime import datetime

def log(message):
    print(datetime.now().strftime("%H:%M:%S -"), message)
    
def printnow():
    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print("Current Time =", current_time)

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier

In [3]:
names = ["Linear SVM (OvR)", "Nearest Neighbors (OvR)",
         "RBF SVM (OvR)", 
         "Gaussian Process (OvR)", "Decision Tree (OvR)", "Random Forest (OvR)", "Neural Net (OvR)",
         "AdaBoost (OvR)", "Naive Bayes (OvR)", "QDA (OvR)",
         "Linear SVM (OvO)", "Nearest Neighbors (OvO)",
         "RBF SVM (OvO)", 
         "Gaussian Process (OvO)", "Decision Tree (OvO)", "Random Forest (OvO)", "Neural Net (OvO)",
         "AdaBoost (OvO)", "Naive Bayes (OvO)", "QDA (OvO)"]

In [4]:
def make_classifier(num):
    if num == 0:
        return OneVsRestClassifier(SVC(kernel="linear", C=0.025), n_jobs = -1)
    elif num == 1:
        return OneVsRestClassifier(KNeighborsClassifier(3))
    elif num == 2:
        return OneVsRestClassifier(SVC(gamma=2, C=1), n_jobs = -1)
    elif num == 3:
        return OneVsRestClassifier(GaussianProcessClassifier(1.0 * RBF(1.0)), n_jobs = -1)
    elif num == 4:
        return OneVsRestClassifier(DecisionTreeClassifier(max_depth=5), n_jobs = -1)
    elif num == 5:
        return OneVsRestClassifier(RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1), n_jobs = -1)
    elif num == 6:
        return OneVsRestClassifier(MLPClassifier(alpha=1, max_iter=1000), n_jobs = -1)
    elif num == 7:
        return OneVsRestClassifier(AdaBoostClassifier(), n_jobs = -1)
    elif num == 8:
        return OneVsRestClassifier(GaussianNB(), n_jobs = -1)
    elif num == 9:
        return OneVsRestClassifier(QuadraticDiscriminantAnalysis(), n_jobs = -1)
    elif num == 10:
        return OneVsOneClassifier(KNeighborsClassifier(3))
    elif num == 11:
        return OneVsOneClassifier(SVC(kernel="linear", C=0.025))
    elif num == 12:
        return OneVsOneClassifier(SVC(gamma=2, C=1))
    elif num == 13:
        return OneVsOneClassifier(GaussianProcessClassifier(1.0 * RBF(1.0)))
    elif num == 14:
        return OneVsOneClassifier(DecisionTreeClassifier(max_depth=5))
    elif num == 15:
        return OneVsOneClassifier(RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1))
    elif num == 16:
        return OneVsOneClassifier(MLPClassifier(alpha=1, max_iter=1000))
    elif num == 17:
        return OneVsOneClassifier(AdaBoostClassifier())
    elif num == 18:
        return OneVsOneClassifier(GaussianNB())
    elif num == 19:
        return OneVsOneClassifier(QuadraticDiscriminantAnalysis())
    else:
        return None

    

In [5]:
# printnow()
# X = pd.read_csv('onehot_x.csv')
# printnow()
# Y = pd.read_csv('onehot_y.csv')
# printnow()

log('Reading training and testing One-Hot encodings')
onehot_train = pd.read_pickle('train_test_encoded/onehot_train.zip')
onehot_test = pd.read_pickle('train_test_encoded/onehot_test.zip')
log('Done\n')

printnow()
X_train = onehot_train.drop(columns=['y'])
y_train = onehot_train['y']

X_test = onehot_test.drop(columns=['y'])
y_test = onehot_test['y']
printnow()


15:36:47 - Reading training and testing One-Hot encodings
15:36:50 - Done

Current Time = 15:36:50
Current Time = 15:36:50


In [10]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)


(3936, 14758)
(3936,)
(985, 14758)
(985,)


(985, 14758)

In [6]:
X.shape

(4910, 59396)

In [7]:
Y.head()

0
0  country
1  country
2  country
3  country
4  country

In [18]:
# ASSESS EACH CLASSIFIER, PRINT SCORES (all other parts must be completed first)
printnow()

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=0)
start = 19
stop = 20
for name, clf_index in zip(names[start:stop], range(start,stop)):
    printnow()
    print(name)

    for i in range(0,1): # multiple loops of same classifier (don't recommend more than 1)

        clf = make_classifier(clf_index)
        clf.fit(X_train, Y_train)
        printnow()
        
        y_pred = clf.predict(X_test)
        accuracy = accuracy_score(Y_test, y_pred) # not normalized, gives float (percentage)
        print("acc:\t", accuracy)
        print(classification_report(Y_test, y_pred))
        print('-' * 20)
        print(confusion_matrix(Y_test, y_pred))
        
        del clf
#             print()

#             accuracy = accuracy_score(Y_test, y_pred) # not normalized, gives float (percentage)
#             recall = recall_score(Y_test, y_pred, average='macro') # unweighted average taken
#             precision = precision_score(Y_test, y_pred, average='macro') # unweighted average taken

#             def fancy(x):
#                 print(('%.2f' % x).lstrip('0'))   

#             # some print function (or print to file)
#             print(name, ": ",
#                   "\tscore: ", fancy(accuracy),
#                   "\trecall: ", fancy(recall),
#                   "\tprecision: ", fancy(precision),
#                   "\t", str(i), "th iteration")
printnow()

Current Time = 22:10:44
Current Time = 22:10:45
QDA (OvO)


/home/daniel/Environments/nlpenv3.7.5/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/daniel/Environments/nlpenv3.7.5/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/daniel/Environments/nlpenv3.7.5/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/daniel/Environments/nlpenv3.7.5/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/daniel/Environments/nlpenv3.7.5/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Va

Current Time = 22:13:31
acc:	 0.1894093686354379
              precision    recall  f1-score   support

     country       0.23      0.49      0.31       105
      hiphop       0.09      0.03      0.05       132
         pop       0.18      0.28      0.22       124
        rock       0.10      0.02      0.04       130

    accuracy                           0.19       491
   macro avg       0.15      0.21      0.15       491
weighted avg       0.15      0.19      0.14       491

--------------------
[[51  5 43  6]
 [61  4 61  6]
 [45 29 35 15]
 [63  7 57  3]]
Current Time = 22:13:46


In [10]:
range(0,1)

range(0, 1)

In [11]:
from sklearn.metrics import classification_report
y_true = ['blue', 'green', 'red', 'red', 'red']
y_pred = ['blue', 'blue', 'red', 'red', 'green']
# target_names = ['class 0', 'class 1', 'class 2']
print(confusion_matrix(y_true, y_pred))

[[1 0 0]
 [1 0 0]
 [0 1 2]]


In [21]:
l = [1,2,3]
l2 = [4,5,6]
l_of_l = [l, l2]

for listt in l_of_l:
    print(listt)
    for item in listt:
        print(item)
    del listt
    print(len(l_of_l))
print(l_of_l)

[1, 2, 3]
1
2
3
2
[4, 5, 6]
4
5
6
2
[[1, 2, 3], [4, 5, 6]]
